# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c1c537c9428f144e0f11bffb041ceb4ccd1dcd04f306ea539cfd7aa78cf7ea1a8c6cbeb1483e6169097dc6c1b8987b9e1d77db5f0a66bc65b4ad61ce6e7cf7e

test:
  secret_key_base: b8bfa6bf65dcc768763d114b6640813e65f1ca367e6afe9b907020a80ba2aca58a9d9a81afb6c597806814fef8037c89040aaadcacc5dddf881115198e5ca6e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
